web:
  image: icemaze/dbmysql:dev.2018
  container_name: dev.beaver.test
  #net: rc.net
  ports:
  - "192.168.99.100:80:80"
  extra_hosts:
  - "dev.beaver:192.168.99.100"
  volumes:
  - /mnt/dm-sync/dev/app:/app
  - /mnt/dm-sync/dev/mysql:/var/lib/mysql
  mem_limit: 512m
  memswap_limit: 2000000000
  domainname: rewardcentre
  hostname: dev
  ipc: host
  mac_address: 02:42:ac:11:65:43
  privileged: true
rc:
  image: icemaze/dbmysql:rc.u12
  container_name: rc.u12.test
  domainname: rewardcentre
  hostname: rc.dev
  ipc: host
  ports:
  - "192.168.99.102:80:80"
  extra_hosts:
  - "dev.rc:192.168.99.102"
  
  volumes:
  - /mnt/dm-sync/rc.u12/app:/app
  - /mnt/dm-sync/rc.u12/mysql:/var/lib/mysql
  mem_limit: 512m
  memswap_limit: 2000000000
  privileged: true



  